### ISSUE TITLE
The optimization variable is not compatible to apply function of optimizer

### ISSUE THREAD

**Issue by markliou** [markliou/ML-practice#4]
Traceback (most recent call last):
  File "/workspace/cnn_kc.py", line 130, in <module>
    main()    
    ^^^^^^
  File "/workspace/cnn_kc.py", line 122, in main
    loss, state = trainer(state, cImg, cLab)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/cnn_kc.py", line 104, in trainer
    sTrainableVars, sOptVars = opt.stateless_apply(grads, sTrainableVars, sOptVars)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/keras_core/src/optimizers/base_optimizer.py", line 289, in stateless_apply
    raise ValueError(
ValueError: Argument `optimizer_variables` must be a list of tensors corresponding 1:1 to AdamW().variables. Received list with length 10, but expected 22 variables.

**Comment by markliou** [comment]
This issue is somehow due to the jit function. If the training step is decorated with @jax.jit, the same code can get into the training process.
